# 넘파이 ndarray 개요

In [11]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
print("array1 type:", type(array1))
print("array1 array 형태:", array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [5]:
array2 = np.array([[1,2,3],
                 [2,3,4]])
print("array2 type:", type(array2))
print("array2 array 형태:", array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [6]:
array3 = np.array([[1,2,3]])
print("array3 type:", type(array3))
print("array3 array 형태:", array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


-----------------------------------------------------------------------------------------------------------

**넘파이의 기반 데이터 타입은 ndarray입니다.** 

ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있습니다.<br>
넘파이 array()함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarry로 변환하는 기능을 수행합니다.<br>
생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플형태로 가지고 있으며, 이를 통해 ndarray 배열의 차원까지 알 수 있습니다 

In [7]:
print("array1: {:0}차원, array2: {:1}차원, array3: {:2}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


np.array()사용법은 매우 간단합니다. ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환합니다.

ndarray.shape은 ndarray의 차원과 크기를 튜플 형태로 나타내줍니다. 

array1 은 (3,) = 1차원 array로 3개의 데이터를 가지고 있음<br>
array2 은 (2,3) = 2차원 array로 2개의 로우와 3개의 칼럼<br>
array3 은 (1,3) = 2차원 array로 1개의 로우와 3개의 칼럼<br>

array3 과 array1은 동일한 데이터 건수를 가지고 있지만,<br>
array1은 명확하게 1차원임을 (3,)형태로 표현한 것이며 array3 역시 명확하게 로우와 칼럼으로 이뤄진 2차원 데이터임을 표현


array1은 1차원, array3은 2차원임을 알 수 있습니다. array()함수의 인자로는 파이썬의 리스트 객체가 주로 사용됩니다.<br>
리스트[]는 1차원이고, 리스트의 리스트 [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있기 때문입니다

# ndarray의 데이터 타입

'array()함수의 인자로는 파이썬의 리스트 객체가 주로 사용됩니다'

ndarray내의 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능합니다.<br>
하지만 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없습니다.<br>
ndarray내의 데이터 타입은 dtype 속성으로 확인할 수 있습니다.

In [18]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


서로 다른 데이터 타입을 가질 수 있는 리스트와 다르게,<br> 
ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능<br>
-> 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용 

- " int+string = string "<br>
- " int+float = float "<br>

In [19]:
list2 = [1,2,"test"] 
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U21


In [21]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


ndarray 내 데이터값의 타입 변경 => astype()메서드 이용<br>
주의_float를 int형으로 변경할 때 소수점 이하는 당연히 모두 없어짐<br>

In [22]:
array_int = np.array([1,2,3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [23]:
array_int1=array_float.astype("int32")
print(array_int1,array_int1.dtype)

[1 2 3] int32


In [24]:
array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype("int32")
print(array_int2,array_int2.dtype)

[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

## arange

arange()는 함수 이름에서 알 수 있듯이 파이썬 표준 함수인 range()와 유사한 기능을 합니다.<br>
쉽게 생각하면 array를 range()로 표현하는 것입니다. 

In [25]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype , sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [28]:
#추가 - range()

seq = range(10)
sequence_list = list(seq)
print(sequence_list)
print(sequence_array.dtype , sequence_array.shape)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
int64 (10,)


In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
range(10)

range(0, 10)

## zeros( ) & ones() 

zeros()는 함수 인자로 튜플 형태의 shape 값을 입력<br> 
-> 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 반환

유사하게, ones()는 함수 인자로 튜플 형태의 shape 값을 입력<br> 
-> 모든 값을 1로 채운 해당 shape을 가진 ndarray를 반환

함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채움

In [31]:
zero_array = np.zeros((3,2),dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [32]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape( )

In [34]:
array1 = np.arange(10)
print("array1:\n", array1)
print("\n")

array2 = array1.reshape(2,5)
print("array2:\n", array2)
print("\n")

array3 = array1.reshape(5,2)
print("array3:\n", array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]


array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [36]:
array1.reshape(4,3)

#reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생 
#(10,) 데이터를 (4,3) shape 형태로 변경할 수는 없습니다. 

ValueError: cannot reshape array of size 10 into shape (4,3)

In [2]:
# -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줄 수 있다

array1 = np.arange(10)
print(array1)
print("\n")

array2 = array1.reshape(-1,5)
print("array2 shape:", array2.shape)
print(array2)
print("\n")

array3 = array1.reshape(5,-1)
print("array3 shape:", array3.shape)
print(array3)

[0 1 2 3 4 5 6 7 8 9]


array2 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


array3 shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### -1 인자 설명


array2 = array1.reshape(-1,5)<br>
= 로우 인자가 -1, 칼럼 인자가 5<br>
= array1(10개의 1차원 데이터)와 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변화해라 

array3 = array1.reshape(5,-1)<br>
= 로우 인자가 5, 칼럼 인자가 -1<br>
= 10개의 1차원 데이터와 호환될 수 있는 고정된 5개의 로우<br> 
(결국 2개의 칼럼을 가져야함 = 5x2의 2차원 ndarray로 변환해라)

In [39]:
#물론 -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없습니다.
#10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로는 변경할 수 없기 때문

array1 =np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

-----------------------------------------------------------------------------------------------------


-1 인자는 reshape(-1,1)와 같은 형태로 자주 사용됩니다.<br>
reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarry로 변환됨을 보장합니다.<br>
여러 개의 넘파이 ndarry는 "stack"이나 "concat"으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됩니다.



다음 예제는 reshape(-1,1)을 이용해 3차원을 2차원으로, 1차원을 2차원으로 변경합니다<br>
ndarray는 tolist()메서드를 이용해 리스트 자료형으로 변환할 수 있습니다.<br>
때로는 리스트 자료형을 print를 이용해 출력할 때 시각적으로 더 이해하기 쉬울 수 있어서 ndarray를 리스트로 변환해 출력했습니다.<br> 

In [5]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print("array3d:\n", array3d.tolist())
print("\n")

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print("array5:\n", array5.tolist())
print("array5 shape:", array5.shape)
print("\n")

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print("array6:\n", array6.tolist())
print("array6 shape:", array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing) _ 필사

1.특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당위치의 데이터가 반환.<br>
2.슬라이싱 : 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식.<br>
          ":" 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환.<br>
          예를 들어 1:5라고 하면 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환.<br> 
3.팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환.<br>
4.불린 인덱싱 : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환. 

-----------------------------------------------------------------------------------------------------



## 1.단일값 추출

먼저 한 개의 데이터만을 추출하는 방법을 알아보겠습니다.<br>
1개의 데이터값을 선택하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력하면 됩니다.<br> 
간단한 1차원 ndarray에서 한 개의 데이터를 추출하기 위해 데이터값이 1부터 9까지인 9개의 1차원 ndarray를 생성하겠습니다. 

In [6]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print("array1:", array1)

#**index는 0부터 시작**하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print("value:",value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


인덱스는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치의 데이터값을 의미하므로 데이터값 3을 의미합니다.<br>

**array1[2]의 타입은 더 이상 ndarray 타입이 아니고 ndarray 내의 데이터값을 의미합니다.**

인덱스에 마이너스 기호를 이용하면 맨뒤에서부터 데이터를 추출할 수 있습니다.<br>
인덱스 -1은 맨 뒤의 데이터값을 의미합니다. -2는 맨 뒤에서 두번째에 있는 데이터 값입니다.

In [8]:
print("맨 뒤의 값:", array1[-1], "맨 뒤에서 두 번째 값:", array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8



단일 인덱스를 이용해 ndarray 내의 데이터 값도 간단히 수정 가능합니다.


In [9]:
print("이전 array1:", array1) #추가코드
array1[0]=9
array1[8]=0
print("이후 array1:", array1)

이전 array1: [1 2 3 4 5 6 7 8 9]
이후 array1: [9 2 3 4 5 6 7 8 0]




다음으로 다차원 ndarray에서 단일 값을 추출하겠습니다.<br>
3차원 이상의 ndarray에서의 데이터 추출도 2차원 ndarray와 큰 차이가 없으므로<br> 
더 간단한 이해를 위해 2차원 ndarray에서 단일값을 추출하는 것을 예제로 하겠습니다.<br>

1차원과 2차원 ndarray에서의 데이터 접근의 차이는 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하는 것입니다.

앞 예제의 1차원 ndarray를 2차원의 3X3 ndarray로 변환한 후 [row,col]을 이용해 2차원 ndarray에서 데이터를 추출해보겠습니다.

In [10]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print("\n")

print("(row=0, col=0) index가 가리키는 값:", array2d[0,0])
print("(row=0, col=1) index가 가리키는 값:", array2d[0,1])
print("(row=1, col=0) index가 가리키는 값:", array2d[1,0])
print("(row=2, col=2) index가 가리키는 값:", array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(row=0, col=0) index가 가리키는 값: 1
(row=0, col=1) index가 가리키는 값: 2
(row=1, col=0) index가 가리키는 값: 4
(row=2, col=2) index가 가리키는 값: 9


주목해야 할 부분은 axis0과 axis1 입니다.<br> 
axis0은 로우 방향의 축을 의미합니다.<br>
axis1은 칼럼 방향의 축을 의미합니다.<br>
정확히 얘기하자면, 앞 설명에서 지칭한 로우와 칼럼은 넘파이 ndarray에서는 사용되지 않는 방식입니다.<br>
이해를 돕기 위해 로우, 칼럼 형식으로 표현한 것일 뿐, 정확한 표현으로는 axis0, axis1이 맞습니다.<br> 

**[row=0,col=1]인덱싱은 [axis0=0,axis1=1]이 정확한 표현**

2차원이므로 axis0, axis1로 구분되며,<br> 
3차원 ndarray의 경우는 axis0, axis1, axis 2로 3개의 축을 가지게 됩니다. (행, 열, 높이로 이해하면 됩니다)<br>
이런 식으로 넘파이의 다차원 ndarray는 axis 구분을 가지게 됩니다. 

**axis0이 로우방향 축, axis1이 칼럼 방향축임을 이해하는 것은 중요합니다.**<br>
다차원 ndarray의 경우 축에 따른 연산을 지원하기 때문입니다.<br> 
축 기반의 연산에서 axis가 생략되면 axis0을 의미합니다. 

## 2.슬라이싱
":" 기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있습니다.<br> 
단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray타입입니다.<br>
":" 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료인덱스-1 위치에 있는 데이터의 ndarray를 반환합니다.

In [12]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


슬라이싱 기호인 ":" 사이의 시작, 종료 인덱스는 생략이 가능합니다. 

- ":" 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주합니다.<br>
- ":" 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주합니다.<br>
- ":" 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/ 맨 마지막 인덱스로 간주합니다.<br>

In [22]:
#추가코드
index=np.arange(0,9)
array1 = np.arange(start=1,stop=10)
print("index=",index)
print("\n")
print("array=",array1)

index= [0 1 2 3 4 5 6 7 8]


array= [1 2 3 4 5 6 7 8 9]


In [23]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


이번에는 2차원 ndarray에서 슬라이싱으로 데이터에 접근해보겠습니다.<br>
2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사하며, 단지 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다릅니다.<br> 

In [30]:
#추가코드 
list1=list[(0,0),(0,1),(0,2)]
list2=list[(1,0),(1,1),(1,2)]
list3=list[(2,0),(2,1),(2,2)]
print("index_2차원")
print(list1)
print(list2)
print(list3)

print("\n")
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print("array2d:\n",array2d)

index_2차원
list[(0, 0), (0, 1), (0, 2)]
list[(1, 0), (1, 1), (1, 2)]
list[(2, 0), (2, 1), (2, 2)]


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print("array2d:\n",array2d)

print("array2d[0:2,0:2]\n", array2d[0:2,0:2])
print("array2d[1:3,0:3]\n", array2d[1:3,0:3])
print("array2d[1:3,:]\n", array2d[1:3,:])
print("array2d[:,:]\n", array2d[:,:])
print("array2d[:2,1:]\n", array2d[:2,1:])
print("array2d[:2,0]\n", array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]



2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환합니다.<br>
즉, array2d[0]과 같이 2차원 뒤에 오는 인덱스를 없애면 로우 축 (axis0)의 첫번째 로우 ndarray를 반환하게 됩니다.<br>
반환되는 ndarray는 1차원입니다. 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환합니다.<br>
(추가; 비슷한 느낌으로 array1d[0]이면 더이상 array가 아닌 단일 value가 됨 <- "단일값 추출")<br>

In [35]:
print("array2d[0]=",array2d[0])
print("array2d[0] shape:", array2d[0].shape)
print("array2d[1]=",array2d[1])
print("array2d[1] shape:", array2d[1].shape)

array2d[0]= [1 2 3]
array2d[0] shape: (3,)
array2d[1]= [4 5 6]
array2d[1] shape: (3,)



## 3.팬시 인덱싱

팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식입니다.<br>
2차원 ndarray에 팬시 인덱싱을 적용하면서 이 기능이 어떻게 동작하는지 살펴보겠습니다.<br> 

In [36]:
#추가코드 
list1=list[(0,0),(0,1),(0,2)]
list2=list[(1,0),(1,1),(1,2)]
list3=list[(2,0),(2,1),(2,2)]
print("index_2차원")
print(list1)
print(list2)
print(list3)

print("\n")
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print("array2d:\n",array2d)

index_2차원
list[(0, 0), (0, 1), (0, 2)]
list[(1, 0), (1, 1), (1, 2)]
list[(2, 0), (2, 1), (2, 2)]


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print("array2d[[0,1],2] =>", array3.tolist())

array4 = array2d[[0,1],0:2]
print("array2d[[0,1],0:2] =>", array4.tolist())

array5 = array2d[[0,1]]
print("array2d[[0,1]] =>", array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


(추가코드 index_2차원 output을 참고해서)<br>

array2d[[0,1],2] 로우 축에 팬시 인덱싱인 [0,1]을 칼럼 축에는 단일 값 인덱싱 2를 적용했습니다.<br>
따라서 (row,col) 인덱스가 (0,2),(1,2)로 적용돼 [3,6]을 반환합니다.

array2d[[0,1],0:2]는 ((0,0),(0,1)),((1,0),(1,1)) 인덱싱이 적용돼 [[1,2],[4,5]]를 반환합니다.

array2d[[0,1]]는 ((0,:),(1,:)) 인덱싱이 적용돼 [[1,2,3],[4,5,6]]을 반환합니다.

## 4.불린 인덱싱 

불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식입니다.<br>
1차원 ndarray [1,2,3,4,5,6,7,8,9]에서 데이터값이 5보다 큰 데이터만 추출하려면 어떻게 하면 될까요?<br>
아마 for loop를 돌면서 값을 하나씩 if '추출값' > 5 비교를 통해서 해당하는 데이터만 추출해야 할 것입니다.<br>
불린 인덱싱을 이용하면 for loop / if else 문보다 훨씬 간단하게 이를 구현할 수 있습니다.<br>
불린 인덱싱은 ndarray의 인덱스를 지정하는 []  내에 조건문을 그대로 기재하기만 하면 됩니다.<br>
다음 예제에서 불린 인덱싱을 바로 적용해보도록 하겠습니다. 

-----------------------------------------------------------------------------------

In [38]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 boolean indexing을 적용
array3 = array1d[array1d>5]
print("array1d:", array1d)
print("array1d>5 불린 인덱싱 결과 값:", array3)

array1d: [1 2 3 4 5 6 7 8 9]
array1d>5 불린 인덱싱 결과 값: [6 7 8 9]



어떻게 조건 필터링이 이처럼 간단하게 될 수 있는지 알아보겠습니다.<br> 
먼저 넘파이 ndarray 객체에 조건식을 할당하면 어떤 일이 일어나는지 확인하겠습니다<br>

In [39]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])


array1d > 5 와 같이 단지 ndarray 객체에 조건식만 붙였을 뿐인데 False, True로 이뤄진 ndarray 객체가 반환됐습니다.<br>
반환된 array([False, False, False, False, False,  True,  True,  True,  True]) 를 자세히 살펴보면,<br>
5보다 큰 데이터가 있는 위치는 True 값이, 그렇지 않는 경우는 False 값이 반환됨을 확인할 수 있습니다.

조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 [] 내에 입력하면 False 값은 무시하고,<br>
True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환하게 됩니다.<br>

즉, array([False, False, False, False, False,  True,  True,  True,  True])에서<br>
False가 있는 인덱스 0~4는 무시하고 인덱스 [5,6,7,8]이 만들어지고 이 위치 인덱스에 해당하는 데이터 세트 [6,7,8,9]를 반환하게 됩니다.

위와 동일한 불린 ndarray를 만들고 이를 array1d[]내에 인덱스로 입력하면 동일한 데이터 세트가 변환됨을 알 수 있습니다. 

In [41]:
boolean_indexs = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexs]
print("불린 인덱스로 필터링 결과 :", array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [43]:
#즉, 다음과 같이 직접 인덱스 집합을 만들어 대입한 것과 동일

indexes =np.array([5,6,7,8])
array4 = array1d[indexes]
print("일반 인덱스로 필터링 결과 :", array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]



step1 : array1d > 5 와 같이 ndarray의 필터링 조건을 [] 안에 기재<br>
step2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장<br> 
(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것입니다)<br>
step3 : 저장된 인덱스 데이터 세트로 ndarray 조회<br>

--------------------------------------------------------------------------------------------------

# 행렬의 정렬 - sort( )와 argsort( )

## 행렬의 정렬<br>
1.np.sort()와 같이 넘파이에서 sort()를 호출하는 방식<br>
2.ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식<br>
1의 경우 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환하며,<br> 
2의 경우 원 행렬 자체를 정렬한 형태로 반한하며 반환 값은 none입니다.<br>

In [14]:
org_array=np.array([3,1,9,5])
print("원본 행렬:", org_array)

# 1-np.sort()로 정렬
sort_array1 = np.sort(org_array)
print("np.sort() 호출 후 반환된 정렬 행렬:", sort_array1)
print("np.sort() 호출 후 원본 행렬:", org_array)

# 2-ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print("org_array.sort 호출 후 반환된 행렬:", sort_array2)
print("org_array.sort 호출 후 원본 행렬:", org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort 호출 후 반환된 행렬: None
org_array.sort 호출 후 원본 행렬: [1 3 5 9]


In [15]:
#내림차순

sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬:", sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [4]:
#행렬이 2차원인 경우

array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d,axis=0)
print("로우 방향으로 정렬: \n", sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print("칼럼 방향으로 정렬:\n", sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [5]:
#추가 예시

myarray = np.array([[10,9],[5,15]])
print(myarray)

[[10  9]
 [ 5 15]]


In [7]:
myarray_0 = np.sort(myarray,axis=0)
print(myarray_0)

[[ 5  9]
 [10 15]]


In [8]:
myarray_1 = np.sort(myarray,axis=1)
print(myarray_1)

[[ 9 10]
 [ 5 15]]



## 정렬된 행렬의 인덱스를 반환하기 

In [11]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스:" , sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [13]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [14]:
import numpy as np

name_array = np.array(["john","mike","sarah","kate","samuel"])
score_array = np.array([78,95,84,98,88])
sort_indices_asc = np.argsort(score_array)

In [17]:
print("성적 오름차순 정렬 시 score_array의 인덱스:", sort_indices_asc)
print("성적 오름차순으로 name_array의 이름 출력:", name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['john' 'sarah' 'samuel' 'mike' 'kate']


# 선형대수 연산 - 행렬 내적과 전치행렬 구하기

## 행렬내적(행렬곱)

In [8]:
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,8],
             [9,10],
             [11,12]])

In [12]:
dot_product = np.dot(A,B)
print("행렬 내적 결과:\n", dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


## 전치행렬

In [13]:
A = np.array([[1,2],
             [3,4]])

transpose_mat = np.transpose(A)
print("A의 전치 행렬:\n", transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
