# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [1]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [16]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common=[]
for i in Z1:
    for j in Z2:
        if i==j:
            common.append(j)
            
result= []
for t in common:
    if t not in result:
        result.append(t)

print(result)

[2, 4, 6, 3]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [39]:
import math

a = np.sqrt(-1)
b = np.emath.sqrt(-1)
math.isclose(a,b)

/var/folders/f4/skyf3wfx5570p30yjkrfkxd00000gn/T/ipykernel_38562/1153015047.py:3: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(-1)
/var/folders/f4/skyf3wfx5570p30yjkrfkxd00000gn/T/ipykernel_38562/1153015047.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  math.isclose(a,b)


False

In [6]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [45]:
Z = np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [14]:
A=10 
B=20

result1=np.multiply(np.add(A,B),np.divide(np.negative(A),2))
result2= ((A+B)*(-A/2))

result1==result2

True

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [11]:
x=2.345
print(x-(x%1))
print((10*x)//10)

2.0
2.0


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [5]:
vector31 = np.random.randint(0,5,size=25)
matrix31 = vector31.reshape(5,5)
print(matrix31)


[[1 0 0 3 4]
 [1 4 3 4 2]
 [0 3 1 1 4]
 [3 0 3 2 0]
 [0 2 3 3 1]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [51]:
ran=np.random.random(10)
print(ran)
ran.sort()
print(ran)

[0.76520582 0.39556341 0.19634301 0.41252671 0.76921558 0.18787068
 0.60849101 0.60911121 0.20098284 0.46130456]
[0.18787068 0.19634301 0.20098284 0.39556341 0.41252671 0.46130456
 0.60849101 0.60911121 0.76520582 0.76921558]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [2]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [40]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.3426326  0.57823437 1.17821449 0.90810172 0.48612373 0.33595348
 0.2952299  0.34425871 0.7606535  0.59002419]
[0.43312454 0.32973974 0.88752194 0.47869691 0.14417522 1.12255541
 0.78731695 1.02634    0.52457357 1.02337218]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [37]:
vector35=np.random.random(10)
vector35.argmax()

3

In [38]:
print("바꾸기 전:",vector35)
vector35[3]=0
print("바꾼 후:",vector35)

바꾸기 전: [0.05263525 0.11201338 0.59363853 0.98252614 0.12261199 0.06086259
 0.67676612 0.72590003 0.41813951 0.61021383]
바꾼 후: [0.05263525 0.11201338 0.59363853 0.         0.12261199 0.06086259
 0.67676612 0.72590003 0.41813951 0.61021383]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [44]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dist = abs(Z-v)
mindex=dist.argmin()
Z[mindex]

27

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [50]:
Z = np.arange(9).reshape(3,3)

for i,j in np.ndenumerate(Z):
    print(i,j)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [45]:
n=5 #size of a 2D array
p=5 #the number of elements that i want to place
Z=np.zeros((5,5))
np.put(Z,np.random.choice(range(5*5),p,replace=False),np.array([115,921,522,303,830]))

In [46]:
Z

array([[  0.,   0.,   0., 522., 921.],
       [  0.,   0.,   0.,   0., 830.],
       [303.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 115.]])

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [29]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[7 9 7]
 [4 1 0]
 [9 6 5]]


In [32]:
# column 1
Z1 = Z[Z[:,0].argsort(),:]
print(Z1)

[[4 1 0]
 [7 9 7]
 [9 6 5]]


In [33]:
# column 2
Z2 = Z[Z[:,1].argsort(),:]
print(Z2)

[[4 1 0]
 [9 6 5]
 [7 9 7]]


In [34]:
# column 3
Z3 = Z[Z[:,2].argsort(),:]
print(Z3)

[[4 1 0]
 [9 6 5]
 [7 9 7]]
