# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [114]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
print("-------------")
print(np.show_config())

1.23.5
-------------
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros =

#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
null_vec = np.zeros(10)
null_vec.size

10

#### 4. How to find the memory size of any array (★☆☆)

In [13]:
print(null_vec.size)
print(null_vec.itemsize)
print("memory=",null_vec.size*null_vec.itemsize)

10
8
memory= 80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
null_vec[4]=1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
vector6 = np.arange(10,50)
print(vector6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
vector7=vector6.tolist()
vector7.reverse()
ans7=np.array(vector7)
print(ans7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
vector8 = np.arange(0,9)
matrix8 = vector8.reshape(3,3)
print(matrix8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [53]:
k=np.array([1,2,0,0,4,0])
np.nonzero(k)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [58]:
idmat=np.identity(3)
print(idmat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [59]:
A = np.random.random(27)
A.reshape(3,3,3)

array([[[0.50043766, 0.70361613, 0.4335424 ],
        [0.69316692, 0.15872325, 0.40822284],
        [0.80987297, 0.68362927, 0.63800671]],

       [[0.06677196, 0.98643057, 0.46094912],
        [0.86687194, 0.96863307, 0.3363682 ],
        [0.32813216, 0.46071289, 0.49222097]],

       [[0.97618111, 0.43173364, 0.05340677],
        [0.73381371, 0.42370143, 0.12225648],
        [0.5494141 , 0.99058577, 0.2218338 ]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [61]:
B = np.random.random(100)
print(B.size)
print(min(B))
print(max(B))

100
0.0011770723867828847
0.9763220332177917


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [68]:
vector13 = np.random.random(30)
print(vector13.size)

30


In [69]:
vector13.mean()

0.5177308975941547

In [71]:
np.mean(vector13)

0.5177308975941547

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [72]:
array2d = np.ones((5,5))
array2d[1:-1,1:-1] = 0
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [64]:
print("0 * np.nan: ",0 * np.nan)
print("np.nan==np.nan: ",np.nan==np.nan)
print("np.inf > np.nan: ",np.inf > np.nan)
print("np.nan-np.nan: ",np.nan-np.nan)
print("np.nan in set([np.nan]): ",np.nan in set([np.nan]))
print("0.3==3*0.1: ",0.3==3*0.1)

0 * np.nan:  nan
np.nan==np.nan:  False
np.inf > np.nan:  False
np.nan-np.nan:  nan
np.nan in set([np.nan]):  True
0.3==3*0.1:  False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [65]:
v = [1,2,3,4]
diagmat = np.diag(v)
print(diagmat)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [73]:
checkb = np.zeros((8,8),dtype=int)
checkb[1::2,::2]=1
checkb[::2,1::2]=1
print(checkb)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [54]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [99]:
vec19 = np.random.random(25)
mat19 = vec19.reshape(5,5)
print(mat19)

[[0.60719091 0.30987706 0.71953735 0.16066597 0.80796306]
 [0.80920594 0.57300851 0.88533741 0.32031434 0.27347383]
 [0.68546408 0.94419998 0.32099156 0.51272237 0.91875794]
 [0.41447229 0.5167519  0.32869049 0.74550951 0.65340463]
 [0.41856326 0.51900724 0.18709856 0.12170723 0.40938598]]


In [101]:
norm=(mat19-np.mean(mat19))/np.std(mat19)

In [107]:
print(norm)

[[ 0.33637185 -0.90351699  0.80489057 -1.52577244  1.17365259]
 [ 1.17883577  0.19382091  1.49632706 -0.85999038 -1.05532951]
 [ 0.6627947   1.74180181 -0.85716618 -0.05759058  1.63570079]
 [-0.46732317 -0.04078622 -0.82505927  0.91320234  0.52909707]
 [-0.4502626  -0.03138075 -1.41554053 -1.68824221 -0.48853463]]


In [109]:
print(round(np.mean(norm),1))
print(round(np.std(norm),1))

-0.0
1.0


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [120]:
np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [82]:
vec1 = np.random.randint(1,5,size=15)
vec2 = np.random.randint(1,5,size=6)
mat1 = vec1.reshape(5,3)
mat2 = vec2.reshape(3,2)
print("mat1")
print(mat1)
print("mat2")
print(mat2)
dot_product = np.dot(mat1,mat2)
print("mat1*mat2")
print(dot_product)

mat1
[[1 1 4]
 [2 2 3]
 [3 1 3]
 [2 3 4]
 [3 1 2]]
mat2
[[3 1]
 [4 3]
 [2 2]]
mat1*mat2
[[15 12]
 [20 14]
 [19 12]
 [26 19]
 [17 10]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [122]:
array1d = np.random.randint(1,11,size=10)
print(array1d)

[ 5  3  2  9  7  4  4 10  7  4]


In [123]:
array1d[(3<array1d)&(array1d<8)] *= -1

In [124]:
array1d

array([-5,  3,  2,  9, -7, -4, -4, 10, -7, -4])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [130]:
print(sum(range(5),-1))
from numpy import * # *은 모든 것의 의미로 통용/ numpy에서 모든 것을 가져온다
print(sum(range(5),-1))

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [126]:
Z = np.array([1,2,3])
print(type(Z))
print(Z.dtype)

<class 'numpy.ndarray'>
int64


In [127]:
Z**Z #인덱스가 동일한 벡터의 요소들끼리 곱한 것 

array([ 1,  4, 27])

In [92]:
2 << Z >> 2 

array([1, 2, 4])

#인터넷참고

정수를 2배로 곱하거나 나누어 계산해 주는 비트단위시프트연산자 <<, >>를 이용할 수 있다.
컴퓨터 내부에는 2진수 형태로 값들이 저장되기 때문에,
2진수 형태로 저장되어 있는 값들을 왼쪽(<<)이나 오른쪽(>>)으로
지정한 비트 수만큼 밀어주면 2배씩 늘어나거나 1/2로 줄어드는데,

왼쪽 비트시프트(<<)가 될 때에는 오른쪽에 0이 주어진 개수만큼 추가되고,
오른쪽 비트시프트(>>)가 될 때에는 왼쪽에 0(0 또는 양의 정수인 경우)이나 1(음의 정수인 경우)이 개수만큼 추가되고,
가장 오른쪽에 있는 1비트는 사라진다.


In [129]:
#추가코드
n = 10
print(n<<1)  #10을 2배 한 값인 20 이 출력된다.
print(n>>1)  #10을 반으로 나눈 값인 5 가 출력된다.
print(n<<2)  #10을 4배 한 값인 40 이 출력된다.
print(n>>2)  #10을 반으로 나눈 후 다시 반으로 나눈 값인 2 가 출력된다.

20
5
40
2


In [93]:
Z <- Z

array([False, False, False])

In [131]:
1j*Z 
#imaginary numbers are real multiples of the imaginary unit (the square root of -1)

array([0.+1.j, 0.+2.j, 0.+3.j])

In [95]:
Z/1/1

array([1., 2., 3.])

In [111]:
R = 3
R<R>R

False

In [112]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [83]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/f4/skyf3wfx5570p30yjkrfkxd00000gn/T/ipykernel_38562/3227561482.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
/var/folders/f4/skyf3wfx5570p30yjkrfkxd00000gn/T/ipykernel_38562/3227561482.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
